language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_API_LEVEL=29
    - ANDROID_BUILD_TOOLS_VERSION=29.0.1
    - ADB_INSTALL_TIMEOUT=20
    - ANDROID_ABI=armeabi-v7a
    - ANDroID_TAG=google_apis
    - ANDROID_EMULATOR_LEVEL=18
    - QEMU_AUDIO_DRV=none
android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
    - tools
    - platform-tools
    - tools
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
    - android=$ANDROID_EMULATOR_LEVEL
    # Additional components
    - etra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    ##- addon-google_apis-google-$ANDROID_API_LEVEL
    - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMULATOR_LEVEL
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
    - "$HOME/.android/build-cache/"

before_script:
  - android list targets
  - echo no | android create avd --force -n test -t "android-"$ANDROID_EMULATOR_LEVEL --abi $ANDROID_ABI --TAG $ANDROID_TAG
  - emulator -avd test -no-window &
  - andriod-wait-for-emulator
  # Prepare pre-accepted licenses to not be promted at installation
  ##- mkdir -p "$ANDROID_HOME/licenses"
  ##- cp ./google-licenses/* "$ANDROID_HOME/licenses/"
script:
  - ./gradlew dependencyCheckAnalyze build
  - adb shell input keyevent 82
  - ./gradlew connectedCheck -PdisablePreDex --stacktrace
after_failure: "cat $TRAVIS_BUILD_DIR/app/gen_build/report/lint-result"